const SET_START_DATE = 'SET_START_DATE';
const SET_END_DATE = 'SET_END_DATE';
const SET_SEARCHED_VALUE = 'SET_SEARCHED_VALUE';

export default {
    SET_START_DATE,
    SET_END_DATE,
    SET_SEARCHED_VALUE,
};
